package ${package}.core.workflow;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.osgi.service.component.annotations.Component;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

/**
 * Turns a JSON Schema-style component spec (see specs/*.json for examples)
 * into the three artifacts a hand-built AEM Forms component needs: a Sling
 * Model, an AEM/HTL component, and a React field component. This is a
 * development-time code generator, not a runtime OSGi service that reads or
 * writes JCR content directly — {@code specPath} and {@code outputPath} are
 * filesystem paths, and {@code outputPath} is expected to be the root of a
 * project generated by this archetype (it must contain sibling core/,
 * ui.apps/, and ui.frontend.react.forms.af/ directories).
 */
@Component(service = SpecToCodeGenerator.class)
public class SpecToCodeGenerator {

    private static final Logger LOG = LoggerFactory.getLogger(SpecToCodeGenerator.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    // core/src/main/java is Velocity-filtered by the archetype itself (see the
    // package declaration above), and this class's generated output is HTL and
    // JS template-literal source that legitimately needs its own dollar-brace
    // interpolation sequences. Those two facts collide: a dollar immediately
    // followed by an open brace, written directly in this .java file's text,
    // gets parsed (and can fail to parse) as a Velocity reference before the
    // archetype is ever generated. Building the sequence at runtime through
    // this helper keeps the two characters apart in the source text, so
    // Velocity never sees them adjacent.
    private static String ref(String expr) {
        return "$" + "{" + expr + "}";
    }

    /**
     * @param specPath    path to a JSON Schema-style spec file (title, type=object,
     *                    properties{name: {type, title, description}})
     * @param outputPath  root of the target project (contains core/, ui.apps/,
     *                    ui.frontend.react.forms.af/)
     * @param basePackage Java package the generated Sling Model is placed under
     *                    (e.g. "com.mycompany" — models go in "<basePackage>.core.models")
     * @param appName     AEM app name the generated component is placed under
     *                    (apps/&lt;appName&gt;/components/generated/&lt;slug&gt;)
     */
    public void generate(String specPath, String outputPath, String basePackage, String appName) throws IOException {
        LOG.info("Invoking Spec-to-Code Generator for spec: {} to output path: {}", specPath, outputPath);

        Path spec = Paths.get(specPath);
        JsonNode root = MAPPER.readTree(spec.toFile());

        String specFileName = spec.getFileName().toString();
        String title = root.hasNonNull("title") ? root.get("title").asText() : specFileName;
        List<SpecField> fields = readFields(root);
        if (fields.isEmpty()) {
            throw new IOException("Spec has no 'properties' to generate from: " + specPath);
        }

        String name = toComponentName(title);
        String slug = toKebabCase(name);
        Path out = Paths.get(outputPath);

        Path modelFile = writeSlingModel(out, basePackage, name, specFileName, fields);
        Path componentDir = writeAemComponent(out, appName, basePackage, name, slug, title, specFileName, fields);
        Path reactFile = writeReactComponent(out, name, slug, specFileName, fields);

        LOG.info("Generated Sling Model: {}", modelFile);
        LOG.info("Generated AEM component: {}", componentDir);
        LOG.info("Generated React component: {}", reactFile);
        LOG.info("Spec-to-Code Generation completed for: {}", specPath);
    }

    private List<SpecField> readFields(JsonNode root) {
        List<SpecField> fields = new ArrayList<>();
        JsonNode properties = root.get("properties");
        if (properties == null || !properties.isObject()) {
            return fields;
        }
        Iterator<Map.Entry<String, JsonNode>> it = properties.fields();
        while (it.hasNext()) {
            Map.Entry<String, JsonNode> entry = it.next();
            JsonNode def = entry.getValue();
            String jsonType = def.hasNonNull("type") ? def.get("type").asText() : "string";
            String fieldTitle = def.hasNonNull("title") ? def.get("title").asText() : entry.getKey();
            String description = def.hasNonNull("description") ? def.get("description").asText() : "";
            fields.add(new SpecField(entry.getKey(), javaType(jsonType), fieldTitle, description));
        }
        return fields;
    }

    private String javaType(String jsonType) {
        switch (jsonType) {
            case "boolean":
                return "Boolean";
            case "integer":
                return "Long";
            case "number":
                return "Double";
            default:
                return "String";
        }
    }

    // --- naming -----------------------------------------------------------

    private String toComponentName(String title) {
        StringBuilder pascal = new StringBuilder();
        for (String word : title.split("[^A-Za-z0-9]+")) {
            if (word.isEmpty()) {
                continue;
            }
            pascal.append(Character.toUpperCase(word.charAt(0))).append(word.substring(1));
        }
        String name = pascal.toString();
        if (name.endsWith("Component") && name.length() > "Component".length()) {
            name = name.substring(0, name.length() - "Component".length());
        }
        return name.isEmpty() ? "GeneratedComponent" : name;
    }

    private String toKebabCase(String pascalName) {
        StringBuilder kebab = new StringBuilder();
        for (int i = 0; i < pascalName.length(); i++) {
            char c = pascalName.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                kebab.append('-');
            }
            kebab.append(Character.toLowerCase(c));
        }
        return kebab.toString();
    }

    private String capitalize(String s) {
        return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    // --- Sling Model --------------------------------------------------------

    private Path writeSlingModel(Path out, String basePackage, String name, String specFileName, List<SpecField> fields) throws IOException {
        StringBuilder src = new StringBuilder();
        src.append("package ").append(basePackage).append(".core.models;\n\n");
        src.append("import org.apache.sling.api.SlingHttpServletRequest;\n");
        src.append("import org.apache.sling.models.annotations.DefaultInjectionStrategy;\n");
        src.append("import org.apache.sling.models.annotations.Model;\n");
        src.append("import org.apache.sling.models.annotations.injectorspecific.ValueMapValue;\n\n");
        src.append("/**\n");
        src.append(" * Generated by SpecToCodeGenerator from ").append(specFileName).append(".\n");
        src.append(" * Regenerate from the spec instead of hand-editing this file.\n");
        src.append(" */\n");
        src.append("@Model(adaptables = SlingHttpServletRequest.class,\n");
        src.append("       defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL)\n");
        src.append("public class ").append(name).append(" {\n\n");
        for (SpecField f : fields) {
            src.append("    @ValueMapValue\n");
            src.append("    private ").append(f.javaType).append(' ').append(f.name).append(";\n\n");
        }
        for (SpecField f : fields) {
            src.append("    public ").append(f.javaType).append(" get").append(capitalize(f.name)).append("() {\n");
            src.append("        return ").append(f.name).append(";\n");
            src.append("    }\n\n");
        }
        src.append("}\n");

        String packagePath = basePackage.replace('.', '/');
        Path modelFile = out.resolve("core/src/main/java/" + packagePath + "/core/models/" + name + ".java");
        Files.createDirectories(modelFile.getParent());
        Files.write(modelFile, src.toString().getBytes(StandardCharsets.UTF_8));
        return modelFile;
    }

    // --- AEM component (content.xml + HTL) -----------------------------------

    private Path writeAemComponent(Path out, String appName, String basePackage, String name, String slug,
            String title, String specFileName, List<SpecField> fields) throws IOException {
        Path componentDir = out.resolve(
                "ui.apps/src/main/content/jcr_root/apps/" + appName + "/components/generated/" + slug);
        Files.createDirectories(componentDir);

        StringBuilder xml = new StringBuilder();
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<jcr:root xmlns:sling=\"http://sling.apache.org/jcr/sling/1.0\" xmlns:cq=\"http://www.day.com/jcr/cq/1.0\" xmlns:jcr=\"http://www.jcp.org/jcr/1.0\"\n");
        xml.append("    jcr:primaryType=\"cq:Component\"\n");
        xml.append("    jcr:title=\"").append(xmlEscape(title)).append("\"\n");
        xml.append("    jcr:description=\"Generated from ").append(xmlEscape(specFileName)).append(" by SpecToCodeGenerator.\"\n");
        xml.append("    sling:resourceSuperType=\"core/wcm/components/teaser/v1/teaser\"\n");
        xml.append("    componentGroup=\"AEM Forms BMAD - ").append(appName).append(" - Generated\"/>\n");
        Files.write(componentDir.resolve(".content.xml"), xml.toString().getBytes(StandardCharsets.UTF_8));

        StringBuilder hasContent = new StringBuilder();
        for (int i = 0; i < fields.size(); i++) {
            if (i > 0) {
                hasContent.append(" || ");
            }
            hasContent.append("model.").append(fields.get(i).name);
        }

        StringBuilder html = new StringBuilder();
        html.append("<sly data-sly-use.model=\"").append(basePackage).append(".core.models.").append(name).append("\"\n");
        html.append("     data-sly-use.template=\"core/wcm/components/commons/v1/templates.html\"\n");
        html.append("     data-sly-test.hasContent=\"").append(ref(hasContent.toString())).append("\">\n");
        html.append("    <div class=\"").append(slug).append("\">\n");
        for (SpecField f : fields) {
            html.append("        <div class=\"").append(slug).append("-field\" data-sly-if=\"")
                    .append(ref("model." + f.name)).append("\">\n");
            html.append("            <span class=\"").append(slug).append("-field-label\">").append(xmlEscape(f.title)).append("</span>\n");
            html.append("            <span class=\"").append(slug).append("-field-value\">")
                    .append(ref("model." + f.name)).append("</span>\n");
            html.append("        </div>\n");
        }
        html.append("    </div>\n");
        html.append("</sly>\n");
        html.append("<sly data-sly-call=\"").append(ref("template.placeholder @ isEmpty=!hasContent")).append("\"></sly>\n");
        Files.write(componentDir.resolve(slug + ".html"), html.toString().getBytes(StandardCharsets.UTF_8));

        return componentDir;
    }

    // --- React component --------------------------------------------------

    private Path writeReactComponent(Path out, String name, String slug, String specFileName, List<SpecField> fields) throws IOException {
        StringBuilder jsx = new StringBuilder();
        jsx.append("import React from 'react';\n");
        jsx.append("import { Field } from '@aemforms/af-react-components';\n\n");
        jsx.append("// Generated by SpecToCodeGenerator from ").append(specFileName).append(".\n");
        jsx.append("// Regenerate from the spec instead of hand-editing this file.\n");
        jsx.append("const ").append(name).append(" = ({\n");
        jsx.append("  label,\n");
        jsx.append("  description,\n");
        jsx.append("  name,\n");
        jsx.append("  value,\n");
        jsx.append("  id,\n");
        jsx.append("  visible,\n");
        jsx.append("  enabled,\n");
        jsx.append("  onChange,\n");
        jsx.append("}) => {\n");
        jsx.append("  if (!visible) {\n");
        jsx.append("    return null;\n");
        jsx.append("  }\n\n");
        jsx.append("  return (\n");
        jsx.append("    <div className=\"").append(slug).append("-field\">\n");
        jsx.append("      <label htmlFor={id} className=\"").append(slug).append("-label\">\n");
        jsx.append("        {label}\n");
        jsx.append("      </label>\n");
        jsx.append("      {description && (\n");
        jsx.append("        <p className=\"").append(slug).append("-description\">{description}</p>\n");
        jsx.append("      )}\n");
        for (SpecField f : fields) {
            jsx.append("      <label className=\"").append(slug).append("-sublabel\">").append(xmlEscape(f.title)).append("</label>\n");
            jsx.append("      <input\n");
            jsx.append("        id={`").append(ref("id")).append('-').append(f.name).append("`}\n");
            jsx.append("        name={`").append(ref("name")).append('.').append(f.name).append("`}\n");
            jsx.append("        type=\"text\"\n");
            jsx.append("        value={(value && value.").append(f.name).append(") || ''}\n");
            jsx.append("        disabled={!enabled}\n");
            jsx.append("        onChange={onChange}\n");
            jsx.append("        className=\"").append(slug).append("-input ").append(slug).append("-").append(f.name).append("\"\n");
            jsx.append("      />\n");
        }
        jsx.append("    </div>\n");
        jsx.append("  );\n");
        jsx.append("};\n\n");
        jsx.append("export default function (props) {\n");
        jsx.append("  // 'Field' handles integration with the AEM Forms rule engine, data binding,\n");
        jsx.append("  // visibility, and enablement based on the Adaptive Form component model.\n");
        jsx.append("  return <Field {...props} render=").append("{").append(name).append("} />;\n");
        jsx.append("}\n");

        Path reactFile = out.resolve(
                "ui.frontend.react.forms.af/src/main/webpack/components/generated/" + name + ".jsx");
        Files.createDirectories(reactFile.getParent());
        Files.write(reactFile, jsx.toString().getBytes(StandardCharsets.UTF_8));
        return reactFile;
    }

    private String xmlEscape(String s) {
        return s.replace("&", "&amp;").replace("\"", "&quot;").replace("<", "&lt;").replace(">", "&gt;");
    }

    private static final class SpecField {
        final String name;
        final String javaType;
        final String title;
        final String description;

        SpecField(String name, String javaType, String title, String description) {
            this.name = name;
            this.javaType = javaType;
            this.title = title;
            this.description = description;
        }
    }
}
