package ${package}.core.workflow;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.osgi.service.component.annotations.Component;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Turns a JSON Schema-style component spec (see specs/*.json for examples)
 * into the three artifacts a hand-built AEM Forms component needs: a Sling
 * Model, an AEM/HTL component, and a React field component. This is a
 * development-time code generator, not a runtime OSGi service that reads or
 * writes JCR content directly — {@code specPath} and {@code outputPath} are
 * filesystem paths, and {@code outputPath} is expected to be the root of a
 * project generated by this archetype (it must contain sibling core/,
 * ui.apps/, and ui.frontend.react.forms.af/ directories).
 *
 * <p>Beyond basic type/title/description, this understands the JSON Schema
 * keywords a real form spec actually needs: {@code required} (spec-level
 * array), {@code format} (email/date/tel/uri — drives the React input's
 * HTML5 type), {@code minLength}/{@code maxLength}/{@code pattern} (string
 * constraints), {@code minimum}/{@code maximum} (numeric constraints), and
 * {@code enum} (renders as a select instead of a text input). Client-side
 * HTML5 constraints alone aren't real validation, so the generated Sling
 * Model also gets a {@code validate()} method that re-checks the same
 * constraints server-side.
 *
 * <p>Also understands three extensions beyond flat scalar fields, each
 * scoped to one level (a nested object's own properties must be scalar; an
 * array's object items must have scalar properties — no object-in-object,
 * no array-in-array):
 * <ul>
 *   <li>{@code "type": "object"} with its own {@code "properties"} — a
 *       nested field group, generated as a separate child Sling Model
 *       ({@code @ChildResource}), inlined as an HTL/React fieldset.</li>
 *   <li>{@code "type": "array"} with {@code "items"} — a repeatable field.
 *       On the Sling Model / HTL side (WCM dialog-authored components) this
 *       is real JCR-backed repetition ({@code @ChildResource List<X>},
 *       {@code data-sly-list}). On the React side, repetition in real
 *       Adaptive Forms is a panel/form-model concern handled by the
 *       renderer (see {@code @aemforms/af-react-renderer}'s
 *       {@code renderChildren}) — a field component's own code is
 *       identical whether it's repeated or not. So this generates a
 *       standalone single-item field (or field-group) component, meant to
 *       be registered in {@code App.jsx}'s {@code customMappings} and
 *       placed inside a form-author-configured repeatable panel; it does
 *       not contain any add/remove logic itself.</li>
 *   <li>{@code "visibleWhen": {"field": "...", "equals": "..."}} on a
 *       scalar field — simple equality-based conditional visibility against
 *       a sibling top-level scalar field.</li>
 * </ul>
 */
@Component(service = SpecToCodeGenerator.class)
public class SpecToCodeGenerator {

    private static final Logger LOG = LoggerFactory.getLogger(SpecToCodeGenerator.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();

    // core/src/main/java is Velocity-filtered by the archetype itself (see the
    // package declaration above), and this class's generated output is HTL and
    // JS template-literal source that legitimately needs its own dollar-brace
    // interpolation sequences. Those two facts collide: a dollar immediately
    // followed by an open brace, written directly in this .java file's text,
    // gets parsed (and can fail to parse) as a Velocity reference before the
    // archetype is ever generated. Building the sequence at runtime through
    // this helper keeps the two characters apart in the source text, so
    // Velocity never sees them adjacent.
    private static String ref(String expr) {
        return "$" + "{" + expr + "}";
    }

    /**
     * @param specPath    path to a JSON Schema-style spec file (title, type=object,
     *                    properties{name: {type, title, description, ...}}, required[])
     * @param outputPath  root of the target project (contains core/, ui.apps/,
     *                    ui.frontend.react.forms.af/)
     * @param basePackage Java package the generated Sling Model is placed under
     *                    (e.g. "com.mycompany" — models go in "<basePackage>.core.models")
     * @param appName     AEM app name the generated component is placed under
     *                    (apps/&lt;appName&gt;/components/generated/&lt;slug&gt;)
     */
    public void generate(String specPath, String outputPath, String basePackage, String appName) throws IOException {
        LOG.info("Invoking Spec-to-Code Generator for spec: {} to output path: {}", specPath, outputPath);

        Path spec = Paths.get(specPath);
        JsonNode root = MAPPER.readTree(spec.toFile());

        String specFileName = spec.getFileName().toString();
        String title = root.hasNonNull("title") ? root.get("title").asText() : specFileName;
        List<SpecField> fields = readFields(root.get("properties"), requiredNames(root), "");
        if (fields.isEmpty()) {
            throw new IOException("Spec has no 'properties' to generate from: " + specPath);
        }
        validateVisibleWhen(fields, specPath);

        String name = toComponentName(title);
        String slug = toKebabCase(name);
        Path out = Paths.get(outputPath);

        Path modelFile = writeSlingModel(out, basePackage, name, specFileName, fields);
        Path componentDir = writeAemComponent(out, appName, basePackage, name, slug, title, specFileName, fields);
        List<Path> reactFiles = writeReactComponents(out, name, slug, specFileName, fields);

        LOG.info("Generated Sling Model: {}", modelFile);
        LOG.info("Generated AEM component: {}", componentDir);
        for (Path reactFile : reactFiles) {
            LOG.info("Generated React component: {}", reactFile);
        }
        LOG.info("Spec-to-Code Generation completed for: {}", specPath);
    }

    /**
     * Generates a complete, real Adaptive Form (a cq:Page with a
     * guideContainer/rootPanel/panels/fields JCR structure, using AEM Forms'
     * standard field components) from a whole-form spec — distinct from
     * {@link #generate}, which produces one reusable custom component.
     *
     * <p>A whole-form spec has a top-level {@code "panels"} array instead of
     * a single {@code "properties"} object; each panel's own {@code
     * "properties"}/{@code "required"} are parsed with the exact same logic
     * a single-component spec's fields already go through.
     *
     * <p>Deliberately scoped: repeatable scalar-array fields and {@code
     * visibleWhen} are not supported for whole-form generation (no verified
     * real JCR shape for either was established for the Core Components
     * format this generates against) and fail the whole generation with a
     * clear error rather than emit a guessed structure. Constraint
     * properties beyond {@code required} (minLength/pattern/minimum/etc.)
     * and a submit action are not emitted this pass either — see README.
     *
     * @param specPath path to a whole-form spec file (title, panels[]: {title, properties, required})
     * @param outputPath root of the target project (contains ui.content/)
     * @param appName AEM app name the generated page is placed under
     *                (content/forms/af/&lt;appName&gt;/&lt;slug&gt;)
     */
    public void generateForm(String specPath, String outputPath, String appName) throws IOException {
        LOG.info("Invoking Spec-to-Code Form Generator for spec: {} to output path: {}", specPath, outputPath);

        Path spec = Paths.get(specPath);
        JsonNode root = MAPPER.readTree(spec.toFile());

        String title = root.hasNonNull("title") ? root.get("title").asText() : spec.getFileName().toString();
        List<SpecPanel> panels = readPanels(root, specPath);
        if (panels.isEmpty()) {
            throw new IOException("Form spec has no 'panels' to generate from: " + specPath);
        }

        String slug = toKebabCase(toComponentName(title));
        Path out = Paths.get(outputPath);

        Path pageFile = writeFormContent(out, appName, slug, title, panels);
        LOG.info("Generated Adaptive Form: {}", pageFile);
        LOG.info("Spec-to-Code Form Generation completed for: {}", specPath);
    }

    private List<SpecPanel> readPanels(JsonNode root, String specPath) throws IOException {
        List<SpecPanel> panels = new ArrayList<>();
        JsonNode panelsNode = root.get("panels");
        if (panelsNode == null || !panelsNode.isArray()) {
            return panels;
        }
        for (JsonNode panelNode : panelsNode) {
            String panelTitle = panelNode.hasNonNull("title") ? panelNode.get("title").asText() : "Panel";
            List<SpecField> fields = readFields(panelNode.get("properties"), requiredNames(panelNode), panelTitle);
            if (fields.isEmpty()) {
                throw new IOException("Panel '" + panelTitle + "' in " + specPath + " has no 'properties' to generate from");
            }
            panels.add(new SpecPanel(panelTitle, fields));
        }
        return panels;
    }

    // --- spec parsing -------------------------------------------------------

    private enum FieldKind { SCALAR, OBJECT, ARRAY_SCALAR, ARRAY_OBJECT }

    private static final class Constraints {
        String format;
        Integer minLength;
        Integer maxLength;
        String pattern;
        Double minimum;
        Double maximum;
        List<String> enumValues = new ArrayList<>();
    }

    private static final class VisibleWhen {
        final String field;
        final String equalsValue;

        VisibleWhen(String field, String equalsValue) {
            this.field = field;
            this.equalsValue = equalsValue;
        }
    }

    // A whole-form spec's top-level "panels" entry — its own title plus the
    // fields parsed via the exact same readFields/readConstraints logic a
    // single-component spec's "properties" already goes through.
    private static final class SpecPanel {
        final String title;
        final List<SpecField> fields;

        SpecPanel(String title, List<SpecField> fields) {
            this.title = title;
            this.fields = fields;
        }
    }

    private static final class SpecField {
        final String name;
        final String title;
        final String description;
        final boolean required;
        final FieldKind kind;
        final String javaType;          // scalar type, or array item's scalar type for ARRAY_SCALAR
        final Constraints constraints;  // applies to SCALAR and ARRAY_SCALAR (per-item)
        final VisibleWhen visibleWhen;  // nullable; SCALAR only
        final List<SpecField> children; // non-null (possibly empty) only for OBJECT / ARRAY_OBJECT
        final String childModelName;    // e.g. "MailingAddress", "Dependent" — set for OBJECT / ARRAY_OBJECT

        SpecField(String name, String title, String description, boolean required, FieldKind kind,
                String javaType, Constraints constraints, VisibleWhen visibleWhen,
                List<SpecField> children, String childModelName) {
            this.name = name;
            this.title = title;
            this.description = description;
            this.required = required;
            this.kind = kind;
            this.javaType = javaType;
            this.constraints = constraints;
            this.visibleWhen = visibleWhen;
            this.children = children;
            this.childModelName = childModelName;
        }
    }

    private Set<String> requiredNames(JsonNode node) {
        Set<String> required = new HashSet<>();
        JsonNode requiredNode = node.get("required");
        if (requiredNode != null && requiredNode.isArray()) {
            for (JsonNode r : requiredNode) {
                required.add(r.asText());
            }
        }
        return required;
    }

    // pathPrefix is used only to make nesting-limit-violation error messages
    // point at the actual offending field (e.g. "address.subAddress").
    private List<SpecField> readFields(JsonNode properties, Set<String> required, String pathPrefix) throws IOException {
        List<SpecField> fields = new ArrayList<>();
        if (properties == null || !properties.isObject()) {
            return fields;
        }

        Iterator<Map.Entry<String, JsonNode>> it = properties.fields();
        while (it.hasNext()) {
            Map.Entry<String, JsonNode> entry = it.next();
            String propName = entry.getKey();
            JsonNode def = entry.getValue();
            String path = pathPrefix.isEmpty() ? propName : pathPrefix + "." + propName;
            String jsonType = def.hasNonNull("type") ? def.get("type").asText() : "string";
            String fieldTitle = def.hasNonNull("title") ? def.get("title").asText() : propName;
            String description = def.hasNonNull("description") ? def.get("description").asText() : "";
            boolean isRequired = required.contains(propName);

            if ("object".equals(jsonType)) {
                List<SpecField> children = readFields(def.get("properties"), requiredNames(def), path);
                rejectNestedContainers(children, path);
                String childModelName = toComponentName(fieldTitle);
                fields.add(new SpecField(propName, fieldTitle, description, isRequired, FieldKind.OBJECT,
                        null, null, null, children, childModelName));

            } else if ("array".equals(jsonType)) {
                JsonNode items = def.get("items");
                String itemJsonType = items != null && items.hasNonNull("type") ? items.get("type").asText() : "string";
                String itemTitle = def.hasNonNull("itemTitle") ? def.get("itemTitle").asText() : fieldTitle;

                if (items != null && "object".equals(itemJsonType)) {
                    List<SpecField> children = readFields(items.get("properties"), requiredNames(items), path + "[]");
                    rejectNestedContainers(children, path + "[]");
                    String childModelName = toComponentName(itemTitle);
                    fields.add(new SpecField(propName, fieldTitle, description, isRequired, FieldKind.ARRAY_OBJECT,
                            null, null, null, children, childModelName));
                } else {
                    Constraints c = items != null ? readConstraints(items) : new Constraints();
                    // "value", not propName - this field is used as the AEM
                    // Forms table/tablerow row-item's own node name
                    // (generateForm) as well as a Java field name (generate).
                    // Reusing propName there would give the row-item field
                    // the same name as its enclosing array/table, which is
                    // confusing and makes the per-row submitted data an
                    // object keyed by the array's own name instead of
                    // something meaningful.
                    SpecField itemField = new SpecField("value", itemTitle, "", false, FieldKind.SCALAR,
                            javaType(itemJsonType), c, null, null, null);
                    fields.add(new SpecField(propName, fieldTitle, description, isRequired, FieldKind.ARRAY_SCALAR,
                            javaType(itemJsonType), c, null, List.of(itemField), null));
                }

            } else {
                Constraints c = readConstraints(def);
                VisibleWhen vw = readVisibleWhen(def);
                fields.add(new SpecField(propName, fieldTitle, description, isRequired, FieldKind.SCALAR,
                        javaType(jsonType), c, vw, null, null));
            }
        }
        return fields;
    }

    // Enforces the one-level nesting limit: a nested object's (or array
    // item's) own fields must all be scalar. Rejecting loudly here beats
    // silently mis-generating a spec that goes deeper than this generator
    // actually supports.
    private void rejectNestedContainers(List<SpecField> children, String path) throws IOException {
        for (SpecField child : children) {
            if (child.kind != FieldKind.SCALAR) {
                throw new IOException("Field '" + path + "." + child.name
                        + "' exceeds the one-level nesting limit this generator supports "
                        + "(nested objects/arrays may only contain scalar fields)");
            }
        }
    }

    private Constraints readConstraints(JsonNode def) {
        Constraints c = new Constraints();
        c.format = def.hasNonNull("format") ? def.get("format").asText() : null;
        c.minLength = def.hasNonNull("minLength") ? def.get("minLength").asInt() : null;
        c.maxLength = def.hasNonNull("maxLength") ? def.get("maxLength").asInt() : null;
        c.pattern = def.hasNonNull("pattern") ? def.get("pattern").asText() : null;
        c.minimum = def.hasNonNull("minimum") ? def.get("minimum").asDouble() : null;
        c.maximum = def.hasNonNull("maximum") ? def.get("maximum").asDouble() : null;
        JsonNode enumNode = def.get("enum");
        if (enumNode != null && enumNode.isArray()) {
            for (JsonNode e : enumNode) {
                c.enumValues.add(e.asText());
            }
        }
        return c;
    }

    private VisibleWhen readVisibleWhen(JsonNode def) {
        JsonNode vw = def.get("visibleWhen");
        if (vw == null || !vw.hasNonNull("field") || !vw.hasNonNull("equals")) {
            return null;
        }
        return new VisibleWhen(vw.get("field").asText(), vw.get("equals").asText());
    }

    // Fails fast on a visibleWhen that can never resolve correctly: an
    // unknown sibling, a non-scalar sibling, or a field referencing itself.
    private void validateVisibleWhen(List<SpecField> topLevelFields, String specPath) throws IOException {
        Map<String, SpecField> byName = new java.util.HashMap<>();
        for (SpecField f : topLevelFields) {
            byName.put(f.name, f);
        }
        for (SpecField f : topLevelFields) {
            if (f.visibleWhen == null) {
                continue;
            }
            String refName = f.visibleWhen.field;
            if (refName.equals(f.name)) {
                throw new IOException("Field '" + f.name + "' in " + specPath + " has visibleWhen referencing itself");
            }
            SpecField target = byName.get(refName);
            if (target == null) {
                throw new IOException("Field '" + f.name + "' in " + specPath
                        + " has visibleWhen referencing unknown field '" + refName + "'");
            }
            if (target.kind != FieldKind.SCALAR) {
                throw new IOException("Field '" + f.name + "' in " + specPath
                        + " has visibleWhen referencing non-scalar field '" + refName + "'");
            }
        }
    }

    private String javaType(String jsonType) {
        switch (jsonType) {
            case "boolean":
                return "Boolean";
            case "integer":
                return "Long";
            case "number":
                return "Double";
            default:
                return "String";
        }
    }

    // Maps a field to the HTML5 input type its React input should use.
    // Numeric fields always render as "number" regardless of a declared
    // format, since that's what makes minimum/maximum meaningful in the
    // browser. Fields with an enum are handled separately as a <select>.
    private String htmlInputType(String javaType, Constraints c) {
        if ("Long".equals(javaType) || "Double".equals(javaType)) {
            return "number";
        }
        String format = c != null ? c.format : null;
        if (format == null) {
            return "text";
        }
        switch (format) {
            case "email":
                return "email";
            case "date":
                return "date";
            case "uri":
                return "url";
            case "tel":
                return "tel";
            default:
                return "text";
        }
    }

    // --- naming -----------------------------------------------------------

    private String toComponentName(String title) {
        StringBuilder pascal = new StringBuilder();
        for (String word : title.split("[^A-Za-z0-9]+")) {
            if (word.isEmpty()) {
                continue;
            }
            pascal.append(Character.toUpperCase(word.charAt(0))).append(word.substring(1));
        }
        String name = pascal.toString();
        if (name.endsWith("Component") && name.length() > "Component".length()) {
            name = name.substring(0, name.length() - "Component".length());
        }
        return name.isEmpty() ? "GeneratedComponent" : name;
    }

    private String toKebabCase(String pascalName) {
        StringBuilder kebab = new StringBuilder();
        for (int i = 0; i < pascalName.length(); i++) {
            char c = pascalName.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                kebab.append('-');
            }
            kebab.append(Character.toLowerCase(c));
        }
        return kebab.toString();
    }

    private String capitalize(String s) {
        return s.isEmpty() ? s : Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    // --- Sling Model --------------------------------------------------------

    private Path writeSlingModel(Path out, String basePackage, String name, String specFileName, List<SpecField> fields) throws IOException {
        // Nested objects and array-of-object fields need their own child
        // Sling Model file, adapted from the child Resource directly (not
        // from the request — ChildResourceInjector adapts the child
        // Resource itself via ModelFactory).
        for (SpecField f : fields) {
            if (f.kind == FieldKind.OBJECT || f.kind == FieldKind.ARRAY_OBJECT) {
                writeModelFile(out, basePackage, f.childModelName, specFileName, f.children, true);
            }
        }
        return writeModelFile(out, basePackage, name, specFileName, fields, false);
    }

    private Path writeModelFile(Path out, String basePackage, String name, String specFileName,
            List<SpecField> fields, boolean isChildModel) throws IOException {
        StringBuilder src = new StringBuilder();
        src.append("package ").append(basePackage).append(".core.models;\n\n");
        if (isChildModel) {
            src.append("import org.apache.sling.api.resource.Resource;\n");
        } else {
            src.append("import org.apache.sling.api.SlingHttpServletRequest;\n");
        }
        src.append("import org.apache.sling.models.annotations.DefaultInjectionStrategy;\n");
        src.append("import org.apache.sling.models.annotations.Model;\n");
        src.append("import org.apache.sling.models.annotations.injectorspecific.ChildResource;\n");
        src.append("import org.apache.sling.models.annotations.injectorspecific.ValueMapValue;\n\n");
        src.append("import java.util.ArrayList;\n");
        src.append("import java.util.Arrays;\n");
        src.append("import java.util.Collections;\n");
        src.append("import java.util.List;\n\n");
        src.append("/**\n");
        src.append(" * Generated by SpecToCodeGenerator from ").append(specFileName).append(".\n");
        src.append(" * Regenerate from the spec instead of hand-editing this file.\n");
        src.append(" */\n");
        src.append("@Model(adaptables = ").append(isChildModel ? "Resource.class" : "SlingHttpServletRequest.class").append(",\n");
        src.append("       defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL)\n");
        src.append("public class ").append(name).append(" {\n\n");
        for (SpecField f : fields) {
            appendFieldDeclaration(src, f);
        }
        for (SpecField f : fields) {
            appendGetter(src, f);
        }
        appendValidateMethod(src, fields);
        src.append("}\n");

        String packagePath = basePackage.replace('.', '/');
        Path modelFile = out.resolve("core/src/main/java/" + packagePath + "/core/models/" + name + ".java");
        Files.createDirectories(modelFile.getParent());
        Files.write(modelFile, src.toString().getBytes(StandardCharsets.UTF_8));
        return modelFile;
    }

    private void appendFieldDeclaration(StringBuilder src, SpecField f) {
        switch (f.kind) {
            case SCALAR:
                src.append("    @ValueMapValue\n");
                src.append("    private ").append(f.javaType).append(' ').append(f.name).append(";\n\n");
                break;
            case OBJECT:
                src.append("    @ChildResource\n");
                src.append("    private ").append(f.childModelName).append(' ').append(f.name).append(";\n\n");
                break;
            case ARRAY_SCALAR:
                src.append("    @ValueMapValue\n");
                src.append("    private ").append(f.javaType).append("[] ").append(f.name).append(";\n\n");
                break;
            case ARRAY_OBJECT:
                src.append("    @ChildResource\n");
                src.append("    private List<").append(f.childModelName).append("> ").append(f.name).append(";\n\n");
                break;
        }
    }

    private void appendGetter(StringBuilder src, SpecField f) {
        String cap = capitalize(f.name);
        switch (f.kind) {
            case SCALAR:
                src.append("    public ").append(f.javaType).append(" get").append(cap).append("() {\n");
                src.append("        return ").append(f.name).append(";\n    }\n\n");
                break;
            case OBJECT:
                src.append("    public ").append(f.childModelName).append(" get").append(cap).append("() {\n");
                src.append("        return ").append(f.name).append(";\n    }\n\n");
                break;
            case ARRAY_SCALAR:
                src.append("    public ").append(f.javaType).append("[] get").append(cap).append("() {\n");
                src.append("        return ").append(f.name).append(";\n    }\n\n");
                break;
            case ARRAY_OBJECT:
                // @ChildResource yields null (not an empty list) when the
                // child resource doesn't exist yet — null-safe so callers
                // (validate(), HTL's data-sly-list) don't need to guard it.
                src.append("    public List<").append(f.childModelName).append("> get").append(cap).append("() {\n");
                src.append("        return ").append(f.name).append(" != null ? ").append(f.name).append(" : Collections.emptyList();\n    }\n\n");
                break;
        }
    }

    // Client-side HTML5 constraints are a UX convenience, not enforcement —
    // anyone can submit past them with a direct POST. This re-checks the
    // same spec constraints server-side so callers (e.g. a form submission
    // servlet) have something real to call before trusting the data.
    private void appendValidateMethod(StringBuilder src, List<SpecField> fields) {
        src.append("    /**\n");
        src.append("     * Re-checks this model's fields against the constraints declared in the\n");
        src.append("     * spec this class was generated from. Returns an empty list if valid.\n");
        src.append("     */\n");
        src.append("    public List<String> validate() {\n");
        src.append("        List<String> errors = new ArrayList<>();\n");
        for (SpecField f : fields) {
            appendFieldValidation(src, f, "        ");
        }
        src.append("        return errors;\n");
        src.append("    }\n\n");
    }

    private void appendFieldValidation(StringBuilder src, SpecField f, String indent) {
        String getter = "get" + capitalize(f.name) + "()";
        boolean guarded = f.visibleWhen != null;
        String innerIndent = guarded ? indent + "    " : indent;

        if (guarded) {
            src.append(indent).append("if (").append(vwJavaCondition(f.visibleWhen)).append(") {\n");
        }

        switch (f.kind) {
            case SCALAR:
                appendScalarValidation(src, getter, f.required, f.title, f.javaType, f.constraints, innerIndent);
                break;
            case OBJECT:
                src.append(innerIndent).append("if (").append(getter).append(" == null) {\n");
                if (f.required) {
                    src.append(innerIndent).append("    errors.add(\"").append(jsonEscape(f.title)).append(" is required\");\n");
                }
                src.append(innerIndent).append("} else {\n");
                src.append(innerIndent).append("    for (String e : ").append(getter).append(".validate()) {\n");
                src.append(innerIndent).append("        errors.add(\"").append(jsonEscape(f.title)).append(": \" + e);\n");
                src.append(innerIndent).append("    }\n");
                src.append(innerIndent).append("}\n");
                break;
            case ARRAY_SCALAR: {
                String loopVar = f.name + "Item";
                src.append(innerIndent).append("if (").append(getter).append(" == null || ").append(getter).append(".length == 0) {\n");
                if (f.required) {
                    src.append(innerIndent).append("    errors.add(\"").append(jsonEscape(f.title)).append(" is required\");\n");
                }
                src.append(innerIndent).append("} else {\n");
                src.append(innerIndent).append("    for (").append(f.javaType).append(' ').append(loopVar).append(" : ").append(getter).append(") {\n");
                appendScalarConstraintChecks(src, loopVar, false, f.title, f.javaType, f.constraints, innerIndent + "        ");
                src.append(innerIndent).append("    }\n");
                src.append(innerIndent).append("}\n");
                break;
            }
            case ARRAY_OBJECT: {
                String loopVar = f.name + "Item";
                String idxVar = f.name + "Index";
                src.append(innerIndent).append("if (").append(getter).append(".isEmpty()) {\n");
                if (f.required) {
                    src.append(innerIndent).append("    errors.add(\"").append(jsonEscape(f.title)).append(" is required\");\n");
                }
                src.append(innerIndent).append("} else {\n");
                src.append(innerIndent).append("    int ").append(idxVar).append(" = 0;\n");
                src.append(innerIndent).append("    for (").append(f.childModelName).append(' ').append(loopVar).append(" : ").append(getter).append(") {\n");
                src.append(innerIndent).append("        for (String e : ").append(loopVar).append(".validate()) {\n");
                src.append(innerIndent).append("            errors.add(\"").append(jsonEscape(f.title)).append("[\" + ").append(idxVar).append(" + \"]: \" + e);\n");
                src.append(innerIndent).append("        }\n");
                src.append(innerIndent).append("        ").append(idxVar).append("++;\n");
                src.append(innerIndent).append("    }\n");
                src.append(innerIndent).append("}\n");
                break;
            }
        }

        if (guarded) {
            src.append(indent).append("}\n");
        }
    }

    private void appendScalarValidation(StringBuilder src, String getter, boolean required, String title,
            String javaType, Constraints c, String indent) {
        boolean isString = "String".equals(javaType);
        if (required) {
            if (isString) {
                src.append(indent).append("if (").append(getter).append(" == null || ").append(getter).append(".isEmpty()) {\n");
            } else {
                src.append(indent).append("if (").append(getter).append(" == null) {\n");
            }
            src.append(indent).append("    errors.add(\"").append(jsonEscape(title)).append(" is required\");\n");
            src.append(indent).append("}\n");
        }
        appendScalarConstraintChecks(src, getter, true, title, javaType, c, indent);
    }

    // Shared by a top-level scalar field's getter call and an array-scalar
    // item's loop variable — same constraint checks, different value
    // expression. nullGuard is false inside a for-each loop over a
    // primitive-boxed array item that's already known non-null from the
    // enclosing loop's array-not-empty check.
    private void appendScalarConstraintChecks(StringBuilder src, String valueExpr, boolean nullGuard,
            String title, String javaType, Constraints c, String indent) {
        if (c == null) {
            return;
        }
        boolean isString = "String".equals(javaType);
        boolean isNumeric = "Long".equals(javaType) || "Double".equals(javaType);
        String guard = nullGuard ? valueExpr + " != null && " : "";

        if (isString && c.minLength != null) {
            src.append(indent).append("if (").append(guard).append(valueExpr).append(".length() < ").append(c.minLength).append(") {\n");
            src.append(indent).append("    errors.add(\"").append(jsonEscape(title)).append(" must be at least ").append(c.minLength).append(" characters\");\n");
            src.append(indent).append("}\n");
        }
        if (isString && c.maxLength != null) {
            src.append(indent).append("if (").append(guard).append(valueExpr).append(".length() > ").append(c.maxLength).append(") {\n");
            src.append(indent).append("    errors.add(\"").append(jsonEscape(title)).append(" must be at most ").append(c.maxLength).append(" characters\");\n");
            src.append(indent).append("}\n");
        }
        if (isString && c.pattern != null) {
            src.append(indent).append("if (").append(guard).append('!').append(valueExpr).append(".matches(\"").append(javaEscape(c.pattern)).append("\")) {\n");
            src.append(indent).append("    errors.add(\"").append(jsonEscape(title)).append(" is not in a valid format\");\n");
            src.append(indent).append("}\n");
        }
        if (isNumeric && c.minimum != null) {
            src.append(indent).append("if (").append(guard).append(valueExpr).append(" < ").append(c.minimum).append(") {\n");
            src.append(indent).append("    errors.add(\"").append(jsonEscape(title)).append(" must be at least ").append(c.minimum).append("\");\n");
            src.append(indent).append("}\n");
        }
        if (isNumeric && c.maximum != null) {
            src.append(indent).append("if (").append(guard).append(valueExpr).append(" > ").append(c.maximum).append(") {\n");
            src.append(indent).append("    errors.add(\"").append(jsonEscape(title)).append(" must be at most ").append(c.maximum).append("\");\n");
            src.append(indent).append("}\n");
        }
        if (isString && !c.enumValues.isEmpty()) {
            StringBuilder literal = new StringBuilder();
            for (int i = 0; i < c.enumValues.size(); i++) {
                if (i > 0) {
                    literal.append(", ");
                }
                literal.append('"').append(javaEscape(c.enumValues.get(i))).append('"');
            }
            src.append(indent).append("if (").append(guard).append('!').append("Arrays.asList(").append(literal).append(").contains(").append(valueExpr).append(")) {\n");
            src.append(indent).append("    errors.add(\"").append(jsonEscape(title)).append(" must be one of: ").append(jsonEscape(String.join(", ", c.enumValues))).append("\");\n");
            src.append(indent).append("}\n");
        }
    }

    private String vwJavaCondition(VisibleWhen vw) {
        return "\"" + javaEscape(vw.equalsValue) + "\".equals(get" + capitalize(vw.field) + "())";
    }

    // --- AEM component (content.xml + HTL) -----------------------------------

    private Path writeAemComponent(Path out, String appName, String basePackage, String name, String slug,
            String title, String specFileName, List<SpecField> fields) throws IOException {
        Path componentDir = out.resolve(
                "ui.apps/src/main/content/jcr_root/apps/" + appName + "/components/generated/" + slug);
        Files.createDirectories(componentDir);

        StringBuilder xml = new StringBuilder();
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<jcr:root xmlns:sling=\"http://sling.apache.org/jcr/sling/1.0\" xmlns:cq=\"http://www.day.com/jcr/cq/1.0\" xmlns:jcr=\"http://www.jcp.org/jcr/1.0\"\n");
        xml.append("    jcr:primaryType=\"cq:Component\"\n");
        xml.append("    jcr:title=\"").append(xmlEscape(title)).append("\"\n");
        xml.append("    jcr:description=\"Generated from ").append(xmlEscape(specFileName)).append(" by SpecToCodeGenerator.\"\n");
        xml.append("    sling:resourceSuperType=\"core/wcm/components/teaser/v1/teaser\"\n");
        xml.append("    componentGroup=\"AEM Forms BMAD - ").append(appName).append(" - Generated\"/>\n");
        Files.write(componentDir.resolve(".content.xml"), xml.toString().getBytes(StandardCharsets.UTF_8));

        StringBuilder hasContent = new StringBuilder();
        for (int i = 0; i < fields.size(); i++) {
            if (i > 0) {
                hasContent.append(" || ");
            }
            hasContent.append("model.").append(fields.get(i).name);
        }

        StringBuilder html = new StringBuilder();
        html.append("<sly data-sly-use.model=\"").append(basePackage).append(".core.models.").append(name).append("\"\n");
        html.append("     data-sly-use.template=\"core/wcm/components/commons/v1/templates.html\"\n");
        html.append("     data-sly-test.hasContent=\"").append(ref(hasContent.toString())).append("\">\n");
        html.append("    <div class=\"").append(slug).append("\">\n");
        for (SpecField f : fields) {
            appendHtlField(html, f, slug, "model.", "    ");
        }
        html.append("    </div>\n");
        html.append("</sly>\n");
        html.append("<sly data-sly-call=\"").append(ref("template.placeholder @ isEmpty=!hasContent")).append("\"></sly>\n");
        Files.write(componentDir.resolve(slug + ".html"), html.toString().getBytes(StandardCharsets.UTF_8));

        return componentDir;
    }

    private void appendHtlField(StringBuilder html, SpecField f, String slug, String pathPrefix, String indent) {
        String ownPath = pathPrefix + f.name;
        switch (f.kind) {
            case SCALAR: {
                String condition = f.visibleWhen != null
                        ? "model." + f.name + " && model." + f.visibleWhen.field + " == '" + htlStringEscape(f.visibleWhen.equalsValue) + "'"
                        : ownPath;
                String label = xmlEscape(f.title) + (f.required ? " *" : "");
                html.append(indent).append("<div class=\"").append(slug).append("-field\" data-sly-if=\"")
                        .append(ref(condition)).append("\">\n");
                html.append(indent).append("    <span class=\"").append(slug).append("-field-label\">").append(label).append("</span>\n");
                html.append(indent).append("    <span class=\"").append(slug).append("-field-value\">")
                        .append(ref(ownPath)).append("</span>\n");
                html.append(indent).append("</div>\n");
                break;
            }
            case OBJECT:
                html.append(indent).append("<div class=\"").append(slug).append("-field\" data-sly-if=\"")
                        .append(ref(ownPath)).append("\">\n");
                html.append(indent).append("    <span class=\"").append(slug).append("-field-label\">").append(xmlEscape(f.title)).append("</span>\n");
                for (SpecField child : f.children) {
                    appendHtlField(html, child, slug, ownPath + ".", indent + "    ");
                }
                html.append(indent).append("</div>\n");
                break;
            case ARRAY_SCALAR:
                html.append(indent).append("<div class=\"").append(slug).append("-field\" data-sly-if=\"")
                        .append(ref(ownPath)).append("\">\n");
                html.append(indent).append("    <span class=\"").append(slug).append("-field-label\">").append(xmlEscape(f.title)).append("</span>\n");
                html.append(indent).append("    <ul class=\"").append(slug).append('-').append(f.name).append("-list\" data-sly-list.item=\"")
                        .append(ref(ownPath)).append("\">\n");
                html.append(indent).append("        <li>").append(ref("item")).append("</li>\n");
                html.append(indent).append("    </ul>\n");
                html.append(indent).append("</div>\n");
                break;
            case ARRAY_OBJECT:
                html.append(indent).append("<div class=\"").append(slug).append("-field\" data-sly-if=\"")
                        .append(ref(ownPath)).append("\">\n");
                html.append(indent).append("    <span class=\"").append(slug).append("-field-label\">").append(xmlEscape(f.title)).append("</span>\n");
                html.append(indent).append("    <div class=\"").append(slug).append('-').append(f.name).append("-list\" data-sly-list.item=\"")
                        .append(ref(ownPath)).append("\">\n");
                for (SpecField child : f.children) {
                    appendHtlField(html, child, slug, "item.", indent + "        ");
                }
                html.append(indent).append("    </div>\n");
                html.append(indent).append("</div>\n");
                break;
        }
    }

    private String htlStringEscape(String s) {
        return s.replace("\\", "\\\\").replace("'", "\\'");
    }

    // --- Adaptive Form (complete form) content.xml ---------------------------

    // Real shape verified this session against the shipped financial-application
    // sample: cq:Page -> jcr:content (cq:PageContent) -> guideContainer ->
    // rootPanel -> items -> panels -> items -> fields. cq:template points at
    // the real, existing page-content template (a generic WCM template - it
    // carries no AEM-Forms-specific policies; the sample's own
    // "standard-application" template reference is a pre-existing dangling
    // reference in this archetype's shipped content, not something to copy).
    private Path writeFormContent(Path out, String appName, String slug, String title, List<SpecPanel> panels) throws IOException {
        Path pageDir = out.resolve("ui.content/src/main/content/jcr_root/content/forms/af/" + appName + "/" + slug);
        Files.createDirectories(pageDir);

        StringBuilder xml = new StringBuilder();
        xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        xml.append("<jcr:root xmlns:sling=\"http://sling.apache.org/jcr/sling/1.0\" xmlns:jcr=\"http://www.jcp.org/jcr/1.0\" xmlns:cq=\"http://www.day.com/jcr/cq/1.0\" xmlns:nt=\"http://www.jcp.org/jcr/nt/1.0\" xmlns:fd=\"http://www.adobe.com/aemfd/fd/1.0\"\n");
        xml.append("    jcr:primaryType=\"cq:Page\">\n");
        xml.append("    <jcr:content\n");
        xml.append("        cq:template=\"/conf/").append(appName).append("/settings/wcm/templates/page-content\"\n");
        xml.append("        jcr:primaryType=\"cq:PageContent\"\n");
        xml.append("        jcr:title=\"").append(xmlEscape(title)).append("\"\n");
        xml.append("        sling:resourceType=\"").append(appName).append("/components/adaptiveForm/page\"\n");
        xml.append("        guideComponentType=\"fd/af/components/page\">\n");
        xml.append("        <guideContainer\n");
        xml.append("            jcr:primaryType=\"nt:unstructured\"\n");
        xml.append("            sling:resourceType=\"").append(appName).append("/components/adaptiveForm/formcontainer\"\n");
        xml.append("            editable=\"{Boolean}true\"\n");
        xml.append("            guideNodeClass=\"guideContainerNode\"\n");
        xml.append("            actionType=\"fd/af/components/guidesubmittype/restendpoint\"\n");
        xml.append("            thankYouOption=\"page\"\n");
        xml.append("            thankYouMessage=\"Thank you for your submission.\">\n");
        xml.append("            <rootPanel\n");
        xml.append("                jcr:primaryType=\"nt:unstructured\"\n");
        xml.append("                sling:resourceType=\"").append(appName).append("/components/adaptiveForm/panel\"\n");
        xml.append("                name=\"rootPanel\"\n");
        xml.append("                paneltype=\"simple\"\n");
        xml.append("                layout=\"wizard\">\n");
        xml.append("                <items jcr:primaryType=\"nt:unstructured\">\n");
        for (int i = 0; i < panels.size(); i++) {
            SpecPanel panel = panels.get(i);
            boolean lastPanel = i == panels.size() - 1;
            String panelName = decapitalize(toComponentName(panel.title)) + "Panel";
            xml.append("                    <").append(panelName).append("\n");
            xml.append("                        jcr:primaryType=\"nt:unstructured\"\n");
            xml.append("                        sling:resourceType=\"").append(appName).append("/components/adaptiveForm/panel\"\n");
            xml.append("                        name=\"").append(panelName).append("\"\n");
            xml.append("                        jcr:title=\"").append(xmlEscape(panel.title)).append("\"\n");
            xml.append("                        layout=\"responsiveGrid\">\n");
            xml.append("                        <items jcr:primaryType=\"nt:unstructured\">\n");
            for (SpecField f : panel.fields) {
                appendFormField(xml, f, appName, "                            ");
            }
            if (lastPanel) {
                appendSubmitButton(xml, appName, "                            ");
            }
            xml.append("                        </items>\n");
            xml.append("                    </").append(panelName).append(">\n");
        }
        xml.append("                </items>\n");
        xml.append("            </rootPanel>\n");
        xml.append("        </guideContainer>\n");
        xml.append("    </jcr:content>\n");
        xml.append("</jcr:root>\n");

        Path pageFile = pageDir.resolve(".content.xml");
        Files.write(pageFile, xml.toString().getBytes(StandardCharsets.UTF_8));
        return pageFile;
    }

    // Real shape confirmed by two independent real sources: the shipped
    // contact-us-form sample (a human-authored page using this same Core
    // Components resourceType family) and actions/submit's own
    // _cq_template.xml (the dialog template AEM Forms Editor itself uses).
    // Omits the dialog template's <fd:rules> block on purpose - it's
    // Rule-Editor bookkeeping keyed to an arbitrary per-instance button
    // name/ID from whenever a human dragged the component in, not
    // something meaningful to copy verbatim. <fd:events click="[submitForm()]"/>
    // is the simpler piece both real sources share identically.
    private void appendSubmitButton(StringBuilder xml, String appName, String indent) {
        xml.append(indent).append("<submitButton\n");
        xml.append(indent).append("    jcr:primaryType=\"nt:unstructured\"\n");
        xml.append(indent).append("    sling:resourceType=\"").append(appName).append("/components/adaptiveForm/actions/submit\"\n");
        xml.append(indent).append("    name=\"submitButton\"\n");
        xml.append(indent).append("    jcr:title=\"Submit\"\n");
        xml.append(indent).append("    fieldType=\"button\"\n");
        xml.append(indent).append("    buttonType=\"submit\"\n");
        xml.append(indent).append("    dorExclusion=\"true\">\n");
        xml.append(indent).append("    <fd:events\n");
        xml.append(indent).append("        jcr:primaryType=\"nt:unstructured\"\n");
        xml.append(indent).append("        click=\"[submitForm()]\"/>\n");
        xml.append(indent).append("</submitButton>\n");
    }

    // Real shape confirmed against the shipped benefits-enrollment sample:
    // an fd:rules node's plain `visible` attribute carries a simple,
    // human-readable boolean expression ("fieldName == 'Value'") that's
    // what the runtime actually evaluates - the much larger `fd:visible`
    // JSON blob seen alongside it in that sample is Rule-Editor authoring
    // bookkeeping (the visual rule's AST), the same relationship already
    // confirmed for the submit button's fd:events vs fd:rules/fd:click.
    // Scoped like the single-component generator's visibleWhen: a bare
    // field-name reference resolves against a sibling within the same
    // panel, not a cross-panel/top-level reference.
    private void appendVisibilityRule(StringBuilder xml, VisibleWhen visibleWhen, String indent) {
        String expression = visibleWhen.field + " == '" + expressionLiteralEscape(visibleWhen.equalsValue) + "'";
        xml.append(indent).append("<fd:rules\n");
        xml.append(indent).append("    jcr:primaryType=\"nt:unstructured\"\n");
        xml.append(indent).append("    visible=\"").append(xmlEscape(expression)).append("\"/>\n");
    }

    // Guards against a spec-provided equalsValue breaking out of the
    // single-quoted string literal in the generated rule expression.
    private String expressionLiteralEscape(String s) {
        return s.replace("'", "\\'");
    }

    private void appendFormField(StringBuilder xml, SpecField f, String appName, String indent) throws IOException {
        switch (f.kind) {
            case SCALAR: {
                String resourceType = standardFieldResourceType(f.javaType, f.constraints);
                String fieldType = standardFieldType(resourceType);
                xml.append(indent).append('<').append(f.name).append('\n');
                xml.append(indent).append("    jcr:primaryType=\"nt:unstructured\"\n");
                xml.append(indent).append("    sling:resourceType=\"").append(appName).append("/components/adaptiveForm/").append(resourceType).append("\"\n");
                xml.append(indent).append("    name=\"").append(f.name).append("\"\n");
                xml.append(indent).append("    fieldType=\"").append(fieldType).append("\"\n");
                xml.append(indent).append("    label=\"").append(xmlEscape(f.title)).append('"');
                if (f.required) {
                    xml.append("\n").append(indent).append("    required=\"{Boolean}true\"");
                }
                if (f.visibleWhen != null) {
                    xml.append(">\n");
                    appendVisibilityRule(xml, f.visibleWhen, indent + "    ");
                    xml.append(indent).append("</").append(f.name).append(">\n");
                } else {
                    xml.append("/>\n");
                }
                break;
            }
            case OBJECT: {
                xml.append(indent).append('<').append(f.name).append('\n');
                xml.append(indent).append("    jcr:primaryType=\"nt:unstructured\"\n");
                xml.append(indent).append("    sling:resourceType=\"").append(appName).append("/components/adaptiveForm/panel\"\n");
                xml.append(indent).append("    name=\"").append(f.name).append("\"\n");
                xml.append(indent).append("    jcr:title=\"").append(xmlEscape(f.title)).append("\"\n");
                xml.append(indent).append("    layout=\"responsiveGrid\">\n");
                xml.append(indent).append("    <items jcr:primaryType=\"nt:unstructured\">\n");
                for (SpecField child : f.children) {
                    appendFormField(xml, child, appName, indent + "        ");
                }
                xml.append(indent).append("    </items>\n");
                xml.append(indent).append("</").append(f.name).append(">\n");
                break;
            }
            case ARRAY_OBJECT:
            case ARRAY_SCALAR: {
                // Real repeatable pattern (verified against the shipped
                // financial-application sample's employmentTable/row1): a
                // table carrying min/maxOccur, with one authored tablerow
                // as the repeating row template. ARRAY_SCALAR reuses this
                // exact same proven structure rather than a separately
                // guessed shape - readFields() already synthesizes a
                // single-item SCALAR SpecField into f.children for
                // ARRAY_SCALAR (the same shape ARRAY_OBJECT's own
                // properties use), so a scalar array is just a table whose
                // row template happens to have one field instead of several.
                xml.append(indent).append('<').append(f.name).append('\n');
                xml.append(indent).append("    jcr:primaryType=\"nt:unstructured\"\n");
                xml.append(indent).append("    sling:resourceType=\"").append(appName).append("/components/adaptiveForm/table\"\n");
                xml.append(indent).append("    name=\"").append(f.name).append("\"\n");
                xml.append(indent).append("    jcr:title=\"").append(xmlEscape(f.title)).append("\"\n");
                xml.append(indent).append("    initialRows=\"{Long}1\"\n");
                xml.append(indent).append("    minOccur=\"{Long}").append(f.required ? 1 : 0).append("\"\n");
                xml.append(indent).append("    maxOccur=\"{Long}10\">\n");
                xml.append(indent).append("    <items jcr:primaryType=\"nt:unstructured\">\n");
                xml.append(indent).append("        <row1\n");
                xml.append(indent).append("            jcr:primaryType=\"nt:unstructured\"\n");
                xml.append(indent).append("            sling:resourceType=\"").append(appName).append("/components/adaptiveForm/tablerow\"\n");
                xml.append(indent).append("            name=\"row1\">\n");
                xml.append(indent).append("            <items jcr:primaryType=\"nt:unstructured\">\n");
                for (SpecField child : f.children) {
                    appendFormField(xml, child, appName, indent + "                ");
                }
                xml.append(indent).append("            </items>\n");
                xml.append(indent).append("        </row1>\n");
                xml.append(indent).append("    </items>\n");
                xml.append(indent).append("</").append(f.name).append(">\n");
                break;
            }
        }
    }

    // Maps a field to a standard AEM Forms field component's resourceType
    // leaf name (folders confirmed to exist under ui.apps/.../adaptiveForm/:
    // textinput, numberinput, emailinput, datepicker, dropdown, checkbox).
    // Pattern-matched from the two directly-confirmed real fieldType values
    // (text-input, number-input) for the others - not independently
    // verified per type against a live instance.
    private String standardFieldResourceType(String javaType, Constraints c) {
        if (!c.enumValues.isEmpty()) {
            return "dropdown";
        }
        if ("Boolean".equals(javaType)) {
            return "checkbox";
        }
        if ("Long".equals(javaType) || "Double".equals(javaType)) {
            return "numberinput";
        }
        String format = c.format;
        if ("email".equals(format)) {
            return "emailinput";
        }
        if ("date".equals(format)) {
            return "datepicker";
        }
        return "textinput";
    }

    // Paired with standardFieldResourceType rather than derived from it by
    // string manipulation - resourceType leaf names don't share a uniform
    // suffix (e.g. "datepicker", "dropdown" don't end in "input" the way
    // "textinput"/"numberinput" do), so stripping/appending "-input" would
    // silently produce wrong values for those. text-input/number-input are
    // directly confirmed real fieldType values (from the shipped
    // financial-application sample); the rest are AEM Forms Core
    // Components' documented field type identifiers, not independently
    // verified against a live instance this pass.
    private String standardFieldType(String resourceType) {
        switch (resourceType) {
            case "textinput": return "text-input";
            case "numberinput": return "number-input";
            case "emailinput": return "email-input";
            case "datepicker": return "date-input";
            case "dropdown": return "drop-down";
            case "checkbox": return "checkbox";
            default: return "text-input";
        }
    }

    private String decapitalize(String s) {
        return s.isEmpty() ? s : Character.toLowerCase(s.charAt(0)) + s.substring(1);
    }

    // --- React component(s) --------------------------------------------------

    // Returns every file written: the main component (scalar + nested-object
    // fields inline), plus one standalone file per array field (scalar or
    // object item) — see the class javadoc for why arrays get their own
    // file instead of inline add/remove logic.
    private List<Path> writeReactComponents(Path out, String name, String slug, String specFileName, List<SpecField> fields) throws IOException {
        List<Path> written = new ArrayList<>();

        List<SpecField> inlineFields = new ArrayList<>();
        List<SpecField> arrayFields = new ArrayList<>();
        for (SpecField f : fields) {
            if (f.kind == FieldKind.ARRAY_SCALAR || f.kind == FieldKind.ARRAY_OBJECT) {
                arrayFields.add(f);
            } else {
                inlineFields.add(f);
            }
        }

        written.add(writeReactFieldGroup(out, name, slug, specFileName, inlineFields));

        for (SpecField arrayField : arrayFields) {
            String itemName = arrayField.kind == FieldKind.ARRAY_OBJECT
                    ? arrayField.childModelName
                    : toComponentName(arrayField.title);
            String itemSlug = toKebabCase(itemName);
            // arrayField.children holds either the object item's real fields
            // (ARRAY_OBJECT) or a singleton list with the one synthetic
            // item field built in readFields (ARRAY_SCALAR) — same shape
            // either way, so both render through the same field-group writer.
            written.add(writeReactFieldGroup(out, itemName, itemSlug, specFileName, arrayField.children));
        }

        return written;
    }

    // Emits one component: a <fieldset> of inputs/selects for scalar fields,
    // recursing inline for nested (non-array) object fields. Used for the
    // spec's main component and for each array field's standalone item
    // component — both are "a group of fields", just at different nesting
    // starting points. Array fields themselves never reach this method
    // directly (see writeReactComponents); their extracted item fields do.
    private Path writeReactFieldGroup(Path out, String name, String slug, String specFileName, List<SpecField> fields) throws IOException {
        StringBuilder jsx = new StringBuilder();
        jsx.append("import React from 'react';\n");
        jsx.append("import { Field } from '@aemforms/af-react-components';\n\n");
        jsx.append("// Generated by SpecToCodeGenerator from ").append(specFileName).append(".\n");
        jsx.append("// Regenerate from the spec instead of hand-editing this file.\n");
        jsx.append("//\n");
        jsx.append("// If this file represents one item of a repeatable array field: this\n");
        jsx.append("// component intentionally contains no add/remove logic. In real Adaptive\n");
        jsx.append("// Forms, repetition is a panel/form-model concern handled by the renderer\n");
        jsx.append("// (see @aemforms/af-react-renderer's renderChildren + the 'repeater'\n");
        jsx.append("// mapping) — a field component's code is identical whether it's repeated\n");
        jsx.append("// or not. To actually make this repeatable: register it in App.jsx's\n");
        jsx.append("// customMappings under its own fieldType key, then configure the\n");
        jsx.append("// containing panel as repeatable (minItems/maxItems) in AEM Forms Editor.\n");
        jsx.append("const ").append(name).append(" = ({\n");
        jsx.append("  label,\n");
        jsx.append("  description,\n");
        jsx.append("  name,\n");
        jsx.append("  value,\n");
        jsx.append("  id,\n");
        jsx.append("  visible,\n");
        jsx.append("  enabled,\n");
        jsx.append("  onChange,\n");
        jsx.append("}) => {\n");
        jsx.append("  if (!visible) {\n");
        jsx.append("    return null;\n");
        jsx.append("  }\n\n");
        jsx.append("  return (\n");
        jsx.append("    <div className=\"").append(slug).append("-field\">\n");
        jsx.append("      <label htmlFor={id} className=\"").append(slug).append("-label\">\n");
        jsx.append("        {label}\n");
        jsx.append("      </label>\n");
        jsx.append("      {description && (\n");
        jsx.append("        <p className=\"").append(slug).append("-description\">{description}</p>\n");
        jsx.append("      )}\n");
        for (SpecField f : fields) {
            appendReactField(jsx, f, slug, "value", "");
        }
        jsx.append("    </div>\n");
        jsx.append("  );\n");
        jsx.append("};\n\n");
        jsx.append("export default function (props) {\n");
        jsx.append("  // 'Field' handles integration with the AEM Forms rule engine, data binding,\n");
        jsx.append("  // visibility, and enablement based on the Adaptive Form component model.\n");
        jsx.append("  return <Field {...props} render=").append("{").append(name).append("} />;\n");
        jsx.append("}\n");

        Path reactFile = out.resolve(
                "ui.frontend.react.forms.af/src/main/webpack/components/generated/" + name + ".jsx");
        Files.createDirectories(reactFile.getParent());
        Files.write(reactFile, jsx.toString().getBytes(StandardCharsets.UTF_8));
        return reactFile;
    }

    // valueAccessor is the already-built JS expression for reading this
    // field's slice of `value` (e.g. "value" at the top level, or
    // "(value && value.address)" one level into a nested object).
    // pathSuffix accumulates a dot-joined logical path for nested (non-array)
    // object fields (e.g. "" at the top level, ".address" one level in) —
    // used to build both the dotted `name` path (form-data addressing) and
    // a hyphenated `id` suffix (DOM id uniqueness) at each leaf.
    private void appendReactField(StringBuilder jsx, SpecField f, String slug, String valueAccessor, String pathSuffix) {
        boolean guarded = f.kind == FieldKind.SCALAR && f.visibleWhen != null;

        if (f.kind == FieldKind.OBJECT) {
            jsx.append("      <fieldset className=\"").append(slug).append('-').append(f.name).append("-group\">\n");
            jsx.append("        <legend>").append(xmlEscape(f.title)).append("</legend>\n");
            String childValueAccessor = "(" + valueAccessor + " && " + valueAccessor + "." + f.name + ")";
            String childPathSuffix = pathSuffix + "." + f.name;
            for (SpecField child : f.children) {
                appendReactField(jsx, child, slug, childValueAccessor, childPathSuffix);
            }
            jsx.append("      </fieldset>\n");
            return;
        }

        if (guarded) {
            // The guarded block below renders more than one sibling element
            // (a <label> and an <input>/<select>) — a JSX expression
            // container like {cond && (...)} needs exactly one root element,
            // so wrap them in a Fragment rather than leaving them adjacent.
            jsx.append("      {(").append(valueAccessor).append(" && ").append(valueAccessor).append(".")
                    .append(f.visibleWhen.field).append(" === '").append(jsEscape(f.visibleWhen.equalsValue)).append("') && (\n");
            jsx.append("      <>\n");
        }

        String fieldTitle = xmlEscape(f.title) + (f.required ? " *" : "");
        jsx.append("      <label className=\"").append(slug).append("-sublabel\">").append(fieldTitle).append("</label>\n");

        String leafPath = pathSuffix + "." + f.name;             // e.g. ".street" or ".address.street"
        String idSuffix = leafPath.replace('.', '-');            // e.g. "-street" or "-address-street"
        String fieldId = "`" + ref("id") + idSuffix + "`";
        String fieldName = "`" + ref("name") + leafPath + "`";
        String className = slug + "-input " + slug + "-" + f.name;
        String valueAccess = "(" + valueAccessor + " && " + valueAccessor + "." + f.name + ") || ''";
        boolean required = f.required;

        if (!f.constraints.enumValues.isEmpty()) {
            jsx.append("      <select\n");
            jsx.append("        id={").append(fieldId).append("}\n");
            jsx.append("        name={").append(fieldName).append("}\n");
            jsx.append("        value={").append(valueAccess).append("}\n");
            jsx.append("        disabled={!enabled}\n");
            jsx.append("        required={").append(required).append("}\n");
            jsx.append("        onChange={onChange}\n");
            jsx.append("        className=\"").append(className).append("\"\n");
            jsx.append("      >\n");
            jsx.append("        <option value=\"\">Select...</option>\n");
            for (String opt : f.constraints.enumValues) {
                jsx.append("        <option value=\"").append(jsEscape(opt)).append("\">").append(xmlEscape(opt)).append("</option>\n");
            }
            jsx.append("      </select>\n");
        } else {
            jsx.append("      <input\n");
            jsx.append("        id={").append(fieldId).append("}\n");
            jsx.append("        name={").append(fieldName).append("}\n");
            jsx.append("        type=\"").append(htmlInputType(f.javaType, f.constraints)).append("\"\n");
            jsx.append("        value={").append(valueAccess).append("}\n");
            jsx.append("        disabled={!enabled}\n");
            jsx.append("        required={").append(required).append("}\n");
            if (f.constraints.minLength != null) {
                jsx.append("        minLength={").append(f.constraints.minLength).append("}\n");
            }
            if (f.constraints.maxLength != null) {
                jsx.append("        maxLength={").append(f.constraints.maxLength).append("}\n");
            }
            if (f.constraints.pattern != null) {
                jsx.append("        pattern=\"").append(jsEscape(f.constraints.pattern)).append("\"\n");
            }
            if (f.constraints.minimum != null) {
                jsx.append("        min={").append(f.constraints.minimum).append("}\n");
            }
            if (f.constraints.maximum != null) {
                jsx.append("        max={").append(f.constraints.maximum).append("}\n");
            }
            jsx.append("        onChange={onChange}\n");
            jsx.append("        className=\"").append(className).append("\"\n");
            jsx.append("      />\n");
        }

        if (guarded) {
            jsx.append("      </>\n");
            jsx.append("      )}\n");
        }
    }

    private String xmlEscape(String s) {
        return s.replace("&", "&amp;").replace("\"", "&quot;").replace("<", "&lt;").replace(">", "&gt;");
    }

    // Escapes a spec-provided string for safe embedding inside a single- or
    // double-quoted JS string literal in generated JSX (e.g. a "pattern" or
    // "enum" value from the spec).
    private String jsEscape(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"").replace("'", "\\'").replace("\n", "\\n");
    }

    // Escapes a spec-provided string for safe embedding inside a Java string
    // literal in the generated Sling Model (e.g. a "pattern" or "enum" value).
    private String javaEscape(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    // Escapes a spec-provided string (title) for safe embedding inside a
    // Java string literal that itself is a user-facing validation message.
    private String jsonEscape(String s) {
        return javaEscape(s);
    }
}
