package ${package}.services.impl;

import ${package}.services.AdobeSignException;
import ${package}.services.AdobeSignOrchestrator;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.AttributeType;
import org.osgi.service.metatype.annotations.Designate;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Real Adobe Sign REST API v6 integration. Uploads a document as a transient
 * document, creates an agreement for signature, checks/records its status,
 * and downloads the final signed document once complete.
 *
 * API shape verified against Adobe's own developer docs (developer.adobe.com/acrobat-sign,
 * github.com/AdobeDocs/adobe-sign) rather than assumed: transientDocuments upload,
 * agreements create/status, agreements/{id}/combinedDocument. Not live-tested against
 * a real Adobe Sign account in this session — see README for what to verify with real
 * credentials.
 */
// Registered under both types: AdobeSignOrchestrator for regular callers,
// and this concrete class so AdobeSignWebhookServlet (a different package)
// can @Reference it directly for recordWebhookStatus()/getClientId() -
// intentionally not on the public interface (see its own javadoc). Caught
// live: without the concrete type here, that @Reference resolves to
// nothing and the webhook servlet's own component never activates.
@Component(service = {AdobeSignOrchestrator.class, AdobeSignOrchestratorImpl.class})
@Designate(ocd = AdobeSignOrchestratorImpl.Config.class)
public class AdobeSignOrchestratorImpl implements AdobeSignOrchestrator {

    private static final Logger LOG = LoggerFactory.getLogger(AdobeSignOrchestratorImpl.class);
    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final int MAX_RETRIES = 2;
    private static final long RETRY_DELAY_MS = 500L;

    @ObjectClassDefinition(
        name = "AEM Forms Adobe Sign Integration Configuration",
        description = "Credentials and endpoints for the real Adobe Sign REST API v6 integration."
    )
    public @interface Config {
        @AttributeDefinition(
            name = "OAuth Client ID",
            description = "Adobe Sign OAuth application client_id. Required unless Integration Key is set.",
            type = AttributeType.STRING
        )
        String client_id() default "";

        @AttributeDefinition(
            name = "OAuth Client Secret",
            description = "Adobe Sign OAuth application client_secret. Required unless Integration Key is set. Stored encrypted (OSGi password type).",
            type = AttributeType.PASSWORD
        )
        String client_secret() default "";

        @AttributeDefinition(
            name = "OAuth Refresh Token",
            description = "Long-lived refresh token obtained via a one-time interactive OAuth authorization (see README) - cannot be generated by this code. Required unless Integration Key is set. Stored encrypted.",
            type = AttributeType.PASSWORD
        )
        String refresh_token() default "";

        @AttributeDefinition(
            name = "Integration Key (dev/test fast path)",
            description = "A static bearer token generated in Adobe Sign's own UI (Account > Personal Preferences > API). If set, used directly instead of the OAuth refresh flow - Adobe's own documented shortcut for development/QA/testing. Stored encrypted.",
            type = AttributeType.PASSWORD
        )
        String integration_key() default "";

        @AttributeDefinition(
            name = "OAuth Token Endpoint",
            description = "Adobe Sign OAuth token/refresh endpoint.",
            type = AttributeType.STRING
        )
        String token_endpoint() default "https://secure.adobesign.com/oauth/v2/token";

        @AttributeDefinition(
            name = "Base URIs Discovery Endpoint",
            description = "Endpoint used to discover the account's region-specific API access point.",
            type = AttributeType.STRING
        )
        String base_uris_endpoint() default "https://api.adobesign.com/api/rest/v6/baseUris";
    }

    private String clientId;
    private String clientSecret;
    private String refreshToken;
    private String integrationKey;
    private String tokenEndpoint;
    private String baseUrisEndpoint;

    HttpClient httpClient = HttpClient.newHttpClient(); // package-private so unit tests can substitute a mock

    private final Object tokenLock = new Object();
    private volatile CachedToken cachedToken;
    private final Map<String, String> webhookStatusCache = new ConcurrentHashMap<>();

    @Activate
    protected void activate(final Config config) {
        this.clientId = config.client_id();
        this.clientSecret = config.client_secret();
        this.refreshToken = config.refresh_token();
        this.integrationKey = config.integration_key();
        this.tokenEndpoint = config.token_endpoint();
        this.baseUrisEndpoint = config.base_uris_endpoint();
    }

    @Override
    public String createAgreement(byte[] documentContent, String documentName, String signerEmail) throws AdobeSignException {
        if (documentContent == null || documentContent.length == 0) {
            throw new AdobeSignException("Cannot create an Adobe Sign agreement with no document content");
        }
        if (signerEmail == null || signerEmail.isBlank()) {
            throw new AdobeSignException("Cannot create an Adobe Sign agreement without a signer email");
        }

        TokenInfo token = getAccessToken();
        String transientDocumentId = uploadTransientDocument(token, documentName, documentContent);
        String agreementId = createAgreementForDocument(token, transientDocumentId, documentName, signerEmail);
        LOG.info("Created Adobe Sign agreement: {}", agreementId);
        return agreementId;
    }

    @Override
    public String getStatus(String agreementId) throws AdobeSignException {
        String cached = webhookStatusCache.get(agreementId);
        if (cached != null) {
            return cached;
        }

        TokenInfo token = getAccessToken();
        HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create(token.apiAccessPoint + "/api/rest/v6/agreements/" + agreementId))
            .header("Authorization", "Bearer " + token.accessToken)
            .header("Accept", "application/json")
            .GET()
            .build();

        HttpResponse<byte[]> response = sendWithRetry(request);
        requireSuccess(response, "fetch status for agreement " + agreementId);

        JsonNode json = parseJson(response.body());
        JsonNode status = json.get("status");
        if (status == null) {
            throw new AdobeSignException("Adobe Sign agreement status response had no status field for: " + agreementId);
        }

        String value = status.asText();
        webhookStatusCache.put(agreementId, value);
        return value;
    }

    @Override
    public byte[] getSignedDocument(String agreementId) throws AdobeSignException {
        TokenInfo token = getAccessToken();
        HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create(token.apiAccessPoint + "/api/rest/v6/agreements/" + agreementId + "/combinedDocument?attachAuditReport=true"))
            .header("Authorization", "Bearer " + token.accessToken)
            .header("Accept", "*/*")
            .GET()
            .build();

        HttpResponse<byte[]> response = sendWithRetry(request);
        requireSuccess(response, "download signed document for agreement " + agreementId);
        return response.body();
    }

    /**
     * Called by AdobeSignWebhookServlet (different package - this class's
     * implementation is intentionally the collaborator here, not the
     * AdobeSignOrchestrator interface, since webhook handling is Adobe
     * Sign-specific plumbing other orchestrator implementations wouldn't share)
     * when a real Adobe Sign webhook event arrives, so getStatus() can return
     * it without an extra API call.
     */
    public void recordWebhookStatus(String agreementId, String status) {
        LOG.info("Recording webhook status for agreement {}: {}", agreementId, status);
        webhookStatusCache.put(agreementId, status);
    }

    public String getClientId() {
        return clientId;
    }

    private String uploadTransientDocument(TokenInfo token, String documentName, byte[] documentContent) throws AdobeSignException {
        String boundary = "----AdobeSignBoundary" + UUID.randomUUID();
        byte[] body = buildMultipartBody(boundary, documentName, documentContent);

        HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create(token.apiAccessPoint + "/api/rest/v6/transientDocuments"))
            .header("Authorization", "Bearer " + token.accessToken)
            .header("Content-Type", "multipart/form-data; boundary=" + boundary)
            .POST(HttpRequest.BodyPublishers.ofByteArray(body))
            .build();

        HttpResponse<byte[]> response = sendWithRetry(request);
        requireSuccess(response, "upload transient document");

        JsonNode json = parseJson(response.body());
        JsonNode id = json.get("transientDocumentId");
        if (id == null) {
            throw new AdobeSignException("Adobe Sign transientDocuments response had no transientDocumentId");
        }
        return id.asText();
    }

    private String createAgreementForDocument(TokenInfo token, String transientDocumentId, String documentName, String signerEmail) throws AdobeSignException {
        ObjectNode payload = MAPPER.createObjectNode();
        payload.putArray("fileInfos").addObject().put("transientDocumentId", transientDocumentId);
        payload.put("name", documentName);
        ObjectNode memberInfo = MAPPER.createObjectNode().put("email", signerEmail);
        ObjectNode participantSet = MAPPER.createObjectNode();
        participantSet.putArray("memberInfos").add(memberInfo);
        participantSet.put("order", 1);
        participantSet.put("role", "SIGNER");
        payload.putArray("participantSetsInfo").add(participantSet);
        payload.put("signatureType", "ESIGN");
        payload.put("state", "IN_PROCESS");

        HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create(token.apiAccessPoint + "/api/rest/v6/agreements"))
            .header("Authorization", "Bearer " + token.accessToken)
            .header("Content-Type", "application/json")
            .POST(HttpRequest.BodyPublishers.ofByteArray(payload.toString().getBytes(StandardCharsets.UTF_8)))
            .build();

        HttpResponse<byte[]> response = sendWithRetry(request);
        requireSuccess(response, "create agreement");

        JsonNode json = parseJson(response.body());
        JsonNode id = json.get("id");
        if (id == null) {
            throw new AdobeSignException("Adobe Sign agreements response had no id");
        }
        return id.asText();
    }

    private byte[] buildMultipartBody(String boundary, String fileName, byte[] fileContent) {
        String crlf = "\r\n";
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            out.write(("--" + boundary + crlf).getBytes(StandardCharsets.UTF_8));
            out.write(("Content-Disposition: form-data; name=\"File-Name\"" + crlf + crlf).getBytes(StandardCharsets.UTF_8));
            out.write((fileName + crlf).getBytes(StandardCharsets.UTF_8));

            out.write(("--" + boundary + crlf).getBytes(StandardCharsets.UTF_8));
            out.write(("Content-Disposition: form-data; name=\"File\"; filename=\"" + fileName + "\"" + crlf).getBytes(StandardCharsets.UTF_8));
            out.write(("Content-Type: application/pdf" + crlf + crlf).getBytes(StandardCharsets.UTF_8));
            out.write(fileContent);
            out.write(crlf.getBytes(StandardCharsets.UTF_8));

            out.write(("--" + boundary + "--" + crlf).getBytes(StandardCharsets.UTF_8));
        } catch (IOException e) {
            // ByteArrayOutputStream never actually throws IOException
            throw new UncheckedIOException(e);
        }
        return out.toByteArray();
    }

    private TokenInfo getAccessToken() throws AdobeSignException {
        synchronized (tokenLock) {
            CachedToken cached = cachedToken;
            if (cached != null && System.currentTimeMillis() < cached.expiryEpochMillis) {
                return new TokenInfo(cached.accessToken, cached.apiAccessPoint);
            }

            String accessToken;
            long expiryEpochMillis;
            if (integrationKey != null && !integrationKey.isBlank()) {
                accessToken = integrationKey;
                expiryEpochMillis = Long.MAX_VALUE;
            } else {
                if (clientId == null || clientId.isBlank() || clientSecret == null || clientSecret.isBlank()
                        || refreshToken == null || refreshToken.isBlank()) {
                    throw new AdobeSignException("Adobe Sign is not configured: set client_id/client_secret/refresh_token, or an integration_key");
                }
                TokenResponse refreshed = refreshAccessToken();
                accessToken = refreshed.accessToken;
                expiryEpochMillis = System.currentTimeMillis() + Math.max(0, refreshed.expiresInSeconds - 60) * 1000L;
            }

            String apiAccessPoint = discoverApiAccessPoint(accessToken);
            cachedToken = new CachedToken(accessToken, apiAccessPoint, expiryEpochMillis);
            return new TokenInfo(accessToken, apiAccessPoint);
        }
    }

    private TokenResponse refreshAccessToken() throws AdobeSignException {
        String form = "grant_type=refresh_token"
            + "&client_id=" + urlEncode(clientId)
            + "&client_secret=" + urlEncode(clientSecret)
            + "&refresh_token=" + urlEncode(refreshToken);

        HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create(tokenEndpoint))
            .header("Content-Type", "application/x-www-form-urlencoded")
            .POST(HttpRequest.BodyPublishers.ofString(form, StandardCharsets.UTF_8))
            .build();

        HttpResponse<byte[]> response = sendWithRetry(request);
        requireSuccess(response, "refresh Adobe Sign OAuth token");

        JsonNode json = parseJson(response.body());
        JsonNode accessToken = json.get("access_token");
        if (accessToken == null) {
            throw new AdobeSignException("Adobe Sign token response had no access_token");
        }
        JsonNode expiresIn = json.get("expires_in");
        return new TokenResponse(accessToken.asText(), expiresIn != null ? expiresIn.asLong() : 3600L);
    }

    private String discoverApiAccessPoint(String accessToken) throws AdobeSignException {
        HttpRequest request = HttpRequest.newBuilder()
            .uri(URI.create(baseUrisEndpoint))
            .header("Authorization", "Bearer " + accessToken)
            .header("Accept", "application/json")
            .GET()
            .build();

        HttpResponse<byte[]> response = sendWithRetry(request);
        requireSuccess(response, "discover Adobe Sign API access point");

        JsonNode json = parseJson(response.body());
        JsonNode apiAccessPoint = json.get("apiAccessPoint");
        if (apiAccessPoint == null) {
            throw new AdobeSignException("Adobe Sign baseUris response had no apiAccessPoint");
        }
        String value = apiAccessPoint.asText();
        return value.endsWith("/") ? value.substring(0, value.length() - 1) : value;
    }

    private HttpResponse<byte[]> sendWithRetry(HttpRequest request) throws AdobeSignException {
        IOException lastIoError = null;
        for (int attempt = 0; attempt <= MAX_RETRIES; attempt++) {
            try {
                HttpResponse<byte[]> response = httpClient.send(request, HttpResponse.BodyHandlers.ofByteArray());
                if (response.statusCode() >= 500 && attempt < MAX_RETRIES) {
                    sleepBeforeRetry();
                    continue;
                }
                return response;
            } catch (IOException e) {
                lastIoError = e;
                if (attempt < MAX_RETRIES) {
                    sleepBeforeRetry();
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                throw new AdobeSignException("Interrupted while calling Adobe Sign API: " + request.uri(), e);
            }
        }
        throw new AdobeSignException("Adobe Sign API call failed after retries: " + request.uri(), lastIoError);
    }

    private void sleepBeforeRetry() throws AdobeSignException {
        try {
            Thread.sleep(RETRY_DELAY_MS);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new AdobeSignException("Interrupted while retrying an Adobe Sign API call", e);
        }
    }

    private void requireSuccess(HttpResponse<byte[]> response, String action) throws AdobeSignException {
        int status = response.statusCode();
        if (status < 200 || status >= 300) {
            String body = new String(response.body(), StandardCharsets.UTF_8);
            throw new AdobeSignException("Failed to " + action + " - Adobe Sign returned HTTP " + status + ": " + body);
        }
    }

    private JsonNode parseJson(byte[] body) throws AdobeSignException {
        try {
            return MAPPER.readTree(body);
        } catch (IOException e) {
            throw new AdobeSignException("Could not parse Adobe Sign API response as JSON", e);
        }
    }

    private static String urlEncode(String value) {
        return java.net.URLEncoder.encode(value == null ? "" : value, StandardCharsets.UTF_8);
    }

    private record TokenInfo(String accessToken, String apiAccessPoint) {
    }

    private record TokenResponse(String accessToken, long expiresInSeconds) {
    }

    private record CachedToken(String accessToken, String apiAccessPoint, long expiryEpochMillis) {
    }
}
